###############################################################
# Author(s): Việt Anh Bùi | https://github.com/vietanhbui2000 #
#            n0k0m3 | https://github.com/n0k0m3               #
###############################################################

name: Build ReTwitter

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Setup Java
      uses: actions/setup-java@v3.3.0
      with:
        distribution: "zulu"
        java-version: "17"
        java-package: jdk

    - name: Download base packages
      run: |
        cd retwitter
        python twitter_download.py

    - name: Compile ReTwitter
      run: |
        cd retwitter
        chmod +x compile_retwitter.sh
        ./compile_retwitter.sh
        echo "date_now=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Sign packages
      run: |
        cd retwitter
        chmod +x sign_packages.sh
        ./sign_packages.sh

    - name: Upload packages
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        draft: true
        title: "r${{ env.date_now }}"
        files: |
          retwitter/output/release/*.apk
