###############################################################
# Author(s): Việt Anh Bùi | https://github.com/vietanhbui2000 #
#            n0k0m3 | https://github.com/n0k0m3               #
###############################################################

name: Build ReTikTok

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Setup Java
      uses: actions/setup-java@v3.3.0
      with:
        distribution: "zulu"
        java-version: "17"
        java-package: jdk

    - name: Download TikTok
      run: |
        cd retiktok
        chmod +x dl_tiktok.sh
        ./dl_tiktok.sh

    - name: Compile ReTikTok
      run: |
        cd retiktok
        chmod +x compile_retiktok.sh
        ./compile_retiktok.sh
        echo "date_now=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Sign ReTikTok
      run: |
        chmod +x revanced/sign_revanced.sh
        ./revanced/sign_revanced.sh

    - name: Upload packages
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        draft: true
        title: "r${{ env.date_now }}"
        files: |
          retiktok/output/release/*.apk
