###############################################################
# Author(s): Việt Anh Bùi | https://github.com/vietanhbui2000 #
#            n0k0m3 | https://github.com/n0k0m3               #
###############################################################

name: Build Revanced

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Setup Java
      uses: actions/setup-java@v3.3.0
      with:
        distribution: "zulu"
        java-version: "17"

    - name: Download base packages
      uses: robinraju/release-downloader@v1.3
      with:
        repository: ${{ github.repository }}
        tag: "base"
        fileName: "*"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Compile Revanced
      run: |
        ./compile_revanced.sh
        echo "date_now=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Upload packages
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        draft: true
        title: "v${{ env.date_now }}"
        files: |
          build/*.apk
          vanced-microG.apk
